id: IC6F06BCD
initial_creation_type: ebook
source_metadata:
  id: RDI-KK-23
  title: རྡོ་རྗེ་རྣལ་འབྱོར་མ་དང་རྒྱལ་བ་རྒྱ་མཚོའི་ལྷ་ཁྲིད་གཅེས་བཏུས།
  author: མཛད་པ་པོ། དཔའ་བོ་གཙུག་ལག་ཕྲེང་བ།, མཛད་པ་པོ། དཔའ་བོ་གཙུག་ལག་རྒྱ་མཚོ།, མཛད་པ་པོ།
    མཁས་གྲུབ་རཱ་ག་ཨ་སྱ།, མཛད་པ་པོ། ཀརྨ་ཚེ་དབང་ཀུན་ཁྱབ།
  authors: &id001
  - མཛད་པ་པོ། དཔའ་བོ་གཙུག་ལག་ཕྲེང་བ།
  - མཛད་པ་པོ། དཔའ་བོ་གཙུག་ལག་རྒྱ་མཚོ།
  - མཛད་པ་པོ། མཁས་གྲུབ་རཱ་ག་ཨ་སྱ།
  - མཛད་པ་པོ། ཀརྨ་ཚེ་དབང་ཀུན་ཁྱབ།
  sku: RDI-KK-23
  cover: RDI-KK-23.jpeg
  volume: {}
  series: དྭགས་བརྒྱུད་སྒྲུབ་པའི་ཐེམ་སྐས་གདམས་ངག་ཕྱོགས་བསྒྲིགས།
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: རྡོ་རྗེ་རྣལ་འབྱོར་མ་དང་རྒྱལ་བ་རྒྱ་མཚོའི་ལྷ་ཁྲིད་གཅེས་བཏུས།
  authors: *id001
  sku: RDI-KK-23
  cover: RDI-KK-23.jpeg
layers:
- Author
- BookNumber
- BookTitle
- Chapter
- Citation
- Commentary
- Footnote
- Sabche
- SubTitle
- Tsawa
- Yigchung
